---
- hosts: compute
  tasks:
    - name: Update apt cache and install deps
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - python3-pip
        - python3-dev
      become: yes
      become_method: sudo
    - name: Install venv
      pip:
        name: virtualenv
      become: yes
      become_method: sudo
    - name: Copy files
      copy:
        src: "{{ item }}"
        dest: /home/{{ ansible_user }}/compute/
      with_items:
        - compute/main.py
        - compute/requirements.txt
    - name: Creates venv directory
      file:
        path: /home/{{ ansible_user }}/compute/venv/
        state: directory
    - name: Install modules in a virtualenv
      pip:
        requirements: /home/{{ ansible_user }}/compute/requirements.txt
        virtualenv: /home/{{ ansible_user }}/compute/venv/
    - name: Template systemd service config
      template:
        src: sysctl.j2
        dest: /etc/systemd/system/compute.service
      become: yes
      become_method: sudo
    - name: Start systemd app service
      systemd: name=compute.service state=restarted enabled=yes daemon_reload=true
      become: yes
      become_method: sudo
